###
POST http://localhost:3000/datos
Content-Type: application/json

{
    "humedad_a": 50.5,
    "temperatura": 24.5,
    "humedad_s": 21.5,
    "intensidad": 2.4
}


###
GET http://localhost:3000/datos